apiVersion: apps/v1
kind: Deployment
metadata:
  name: speeddeployment
spec:
  replicas: 2
  selector:
    matchLabels:
      name: speed
      version: "1.0"
  template:
    metadata:
      labels:
        name: speed
        version: "1.0"
      annotations:
          imageregistry: "https://hub.docker.com/"
          licence: Docker official licence
          warranty: 5 Years
    spec:
      containers:
        - name: speedcontainer
          image: public.ecr.aws/y7o1n7v2/speed:3.0
          ports:
            - name: tomcatport
              containerPort: 8080
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /speed/health/readiness.htm
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /speed/health/liveness.htm
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 10
            failureThreshold: 3
#          resources:
#            requests:
#              cpu: "500m"
#              memory: "512Mi"
#            limits:
#              cpu: "500m"
#              memory: "512Mi"